// Generated by gencpp from file plumbing/AddInts.msg
// DO NOT EDIT!


#ifndef PLUMBING_MESSAGE_ADDINTS_H
#define PLUMBING_MESSAGE_ADDINTS_H

#include <ros/service_traits.h>


#include <plumbing/AddIntsRequest.h>
#include <plumbing/AddIntsResponse.h>


namespace plumbing
{

struct AddInts
{

typedef AddIntsRequest Request;
typedef AddIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddInts
} // namespace plumbing


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::plumbing::AddInts > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::plumbing::AddInts&) { return value(); }
};

template<>
struct DataType< ::plumbing::AddInts > {
  static const char* value()
  {
    return "plumbing/AddInts";
  }

  static const char* value(const ::plumbing::AddInts&) { return value(); }
};


// service_traits::MD5Sum< ::plumbing::AddIntsRequest> should match
// service_traits::MD5Sum< ::plumbing::AddInts >
template<>
struct MD5Sum< ::plumbing::AddIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::plumbing::AddInts >::value();
  }
  static const char* value(const ::plumbing::AddIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::plumbing::AddIntsRequest> should match
// service_traits::DataType< ::plumbing::AddInts >
template<>
struct DataType< ::plumbing::AddIntsRequest>
{
  static const char* value()
  {
    return DataType< ::plumbing::AddInts >::value();
  }
  static const char* value(const ::plumbing::AddIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::plumbing::AddIntsResponse> should match
// service_traits::MD5Sum< ::plumbing::AddInts >
template<>
struct MD5Sum< ::plumbing::AddIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::plumbing::AddInts >::value();
  }
  static const char* value(const ::plumbing::AddIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::plumbing::AddIntsResponse> should match
// service_traits::DataType< ::plumbing::AddInts >
template<>
struct DataType< ::plumbing::AddIntsResponse>
{
  static const char* value()
  {
    return DataType< ::plumbing::AddInts >::value();
  }
  static const char* value(const ::plumbing::AddIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLUMBING_MESSAGE_ADDINTS_H
